### model
model_name_or_path: saves/L08
adapter_name_or_path: saves/L09
template: llama3
finetuning_type: lora
infer_dtype: bfloat16

### export
export_dir: saves/L09
export_size: 5
export_device: cpu
export_legacy_format: false