---
title: "Edmentum Growth Modeling"
output: html_document
date: "2025-02-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(dplyr)
library(ggplot2)
library(lme4)
library(pROC)
library(googledrive)
```

## Load Data

```{r pressure, echo=FALSE}
drive_download(as_id("1M6tur2SD-yJi2q9FS9DwW7A8a0yioeAT"), path = "edmentum.csv", overwrite = TRUE)
# Read the downloaded CSV file into a data frame.
data <- read.csv("edmentum.csv")
#data = read.csv("edmentum_full_02_11.csv")
data <- data[!is.na(data$RaschLogit), ] 
View(data) #2,034,965
set.seed(123)  # Set seed for reproducibility
```

```{r}
unique_ids <- unique(data$StudentID_SF)
# Randomly sample half of these unique IDs
half_ids <- sample(unique_ids, length(unique_ids) /2) #change the size depending on available space
subset_data <- data[data$StudentID_SF %in% half_ids, ]

# Filter the dataframe to keep only rows with the sampled student_ids
subset_data$logT <- log(subset_data$T + 1)
subset_data$log_time_since_last_attempt <- log(subset_data$time_since_last_attempt + 1)
subset_data_omitna <- subset(subset_data, !is.na(logT))
```

```{r}
#Subset Data to train-test
subset_data_omitna <- subset_data_omitna %>%
  mutate(row_id = row_number())
train_data <- subset_data_omitna %>%
  group_by(StudentID_SF) %>%
  sample_frac(0.8) %>%
  ungroup()
test_data <- subset_data_omitna %>%
  filter(!(row_id %in% train_data$row_id))
```


```{r}
#Model with time-varied effect
model_time <- glmer(ItemScore ~ logT + log_time_since_last_attempt + correct_last_attempt + offset(-RaschLogit) + (1 + logT + log_time_since_last_attempt + correct_last_attempt | StudentID_SF),
               family = binomial,
               data = train_data)
```

```{r}
summary(model_time)
#Plot of base model intercept (latent ability)
student_coef <- coef(model_time)$StudentID_SF
ggplot(student_coef, aes(x = `(Intercept)`)) +
  geom_density(fill = "blue", alpha = 0.3, color = "blue", size = 1) +
  labs(x = "Intercept (fixed + random)") +
  theme_minimal()

# Density plot for Slopes
ggplot(student_coef, aes(x = logT)) +
  geom_density(fill = "blue", alpha = 0.3, color = "blue", size = 1) +
  labs(x = "Abiilty Growth of Students") +
  theme_minimal()
```

```{r}
#Make prediction based on estimated model
predicted_probs_time <- predict(model_time, newdata = test_data, type = "response", 
                           allow.new.levels = TRUE)
dup_test_data = test_data
dup_test_data$time_pred <- predicted_probs_time
```

```{r}
roc_obj <- roc(response = test_data$ItemScore, 
               predictor = predicted_probs_time)

# Compute the AUC value
auc_value <- auc(roc_obj)
print(auc_value)
plot(roc_obj, main = paste("ROC Curve (AUC =", round(auc_value, 3), ")"))
```

