### model
model_name_or_path: saves/CC03
adapter_name_or_path: saves/CN02
template: llama3
finetuning_type: lora
infer_dtype: bfloat16

### export
export_dir: saves/CN02
export_size: 5
export_device: cpu
export_legacy_format: false