model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
bf16: true
use_peft: true
lora_alpha: 256
lora_r: 128
lora_dropout: 0.1
lora_target_modules: ["q_proj", "v_proj"]

do_eval: true
eval_strategy: "steps"
eval_on_start: true
eval_steps: 200

dataset_name: stair-lab/dsa_hk231_per_student_sft
dataset_test_split: DT01
dataset_text_field: text
dataset_train_split: train
warmup_ratio: 0.1
save_steps: 200

max_seq_length: 512000
num_train_epochs: 50.0
gradient_accumulation_steps: 32
gradient_checkpointing: true
per_device_train_batch_size: 1
learning_rate: 1.5e-4
logging_steps: 1
lr_scheduler_type: cosine
overwrite_output_dir: true
output_dir: saves/llama3-3b-dsa_hk231
report_to: wandb
ddp_timeout: 180000000

push_to_hub_model_id: "code-insights-dsa_hk231"
push_to_hub_organization: "stair-lab"